# Generated by Django 2.2 on 2019-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0004_auto_20190414_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chatroom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
