# Generated by Django 2.2 on 2019-04-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0005_event_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invitations',
            new_name='newMessages',
        ),
    ]
