# Generated by Django 2.2 on 2019-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0007_user_passhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passHash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
