# Generated by Django 2.2 on 2019-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0008_auto_20190427_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
