# Generated by Django 2.2 on 2019-04-14 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 23, 22, 22, 16461)),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 23, 22, 22, 16435)),
        ),
    ]
