# Generated by Django 2.2 on 2019-04-14 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posterApp', '0002_auto_20190414_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 23, 24, 58, 207455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 23, 24, 58, 207415, tzinfo=utc)),
        ),
    ]
